# -*- coding: utf-8 -*-

################################################################################
## Hand-edited Anima-only General Args form.
## Originally generated from BaseUI.ui; the .ui file is no longer authoritative.
## If you regenerate this file with pyside6-uic, mirror the changes back into the
## .ui or this layout will be lost.
################################################################################

from PySide6.QtCore import (QCoreApplication, QSize, Qt)
from PySide6.QtWidgets import (QCheckBox, QFormLayout, QGridLayout,
    QGroupBox, QHBoxLayout, QLabel, QPushButton,
    QSizePolicy, QTextEdit, QWidget)

from modules.DragDropLineEdit import DragDropLineEdit
from modules.LineEditHighlight import LineEditWithHighlight
from modules.ScrollOnSelect import (ComboBox, DoubleSpinBox, SpinBox)


class Ui_base_args_ui(object):
    def setupUi(self, base_args_ui):
        if not base_args_ui.objectName():
            base_args_ui.setObjectName(u"base_args_ui")
        base_args_ui.resize(675, 600)
        self.gridLayout_3 = QGridLayout(base_args_ui)
        self.gridLayout_3.setObjectName(u"gridLayout_3")

        # ---------------- Models (Anima) ----------------
        self.base_model_box = QGroupBox(base_args_ui)
        self.base_model_box.setObjectName(u"base_model_box")
        sizePolicy_models = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy_models.setHeightForWidth(self.base_model_box.sizePolicy().hasHeightForWidth())
        self.base_model_box.setSizePolicy(sizePolicy_models)
        self.formLayout_3 = QFormLayout(self.base_model_box)
        self.formLayout_3.setObjectName(u"formLayout_3")

        # DiT model (pretrained_model_name_or_path)
        self.base_model_label = QLabel(self.base_model_box)
        self.base_model_label.setObjectName(u"base_model_label")
        self.formLayout_3.setWidget(0, QFormLayout.ItemRole.LabelRole, self.base_model_label)
        self.base_model_selection_hLayout = QHBoxLayout()
        self.base_model_selection_hLayout.setObjectName(u"base_model_selection_hLayout")
        self.base_model_input = DragDropLineEdit(self.base_model_box)
        self.base_model_input.setObjectName(u"base_model_input")
        self.base_model_selection_hLayout.addWidget(self.base_model_input)
        self.base_model_selector = QPushButton(self.base_model_box)
        self.base_model_selector.setObjectName(u"base_model_selector")
        self.base_model_selection_hLayout.addWidget(self.base_model_selector)
        self.formLayout_3.setLayout(0, QFormLayout.ItemRole.FieldRole, self.base_model_selection_hLayout)

        # Qwen3 text encoder
        self.qwen3_model_label = QLabel(self.base_model_box)
        self.qwen3_model_label.setObjectName(u"qwen3_model_label")
        self.formLayout_3.setWidget(1, QFormLayout.ItemRole.LabelRole, self.qwen3_model_label)
        self.qwen3_model_hLayout = QHBoxLayout()
        self.qwen3_model_hLayout.setObjectName(u"qwen3_model_hLayout")
        self.qwen3_model_input = DragDropLineEdit(self.base_model_box)
        self.qwen3_model_input.setObjectName(u"qwen3_model_input")
        self.qwen3_model_hLayout.addWidget(self.qwen3_model_input)
        self.qwen3_model_selector = QPushButton(self.base_model_box)
        self.qwen3_model_selector.setObjectName(u"qwen3_model_selector")
        self.qwen3_model_hLayout.addWidget(self.qwen3_model_selector)
        self.formLayout_3.setLayout(1, QFormLayout.ItemRole.FieldRole, self.qwen3_model_hLayout)

        # VAE
        self.vae_label = QLabel(self.base_model_box)
        self.vae_label.setObjectName(u"vae_label")
        self.formLayout_3.setWidget(2, QFormLayout.ItemRole.LabelRole, self.vae_label)
        self.vae_selection_hLayout = QHBoxLayout()
        self.vae_selection_hLayout.setObjectName(u"vae_selection_hLayout")
        self.vae_input = DragDropLineEdit(self.base_model_box)
        self.vae_input.setObjectName(u"vae_input")
        self.vae_selection_hLayout.addWidget(self.vae_input)
        self.vae_selector = QPushButton(self.base_model_box)
        self.vae_selector.setObjectName(u"vae_selector")
        self.vae_selection_hLayout.addWidget(self.vae_selector)
        self.formLayout_3.setLayout(2, QFormLayout.ItemRole.FieldRole, self.vae_selection_hLayout)

        # T5 tokenizer (optional)
        self.t5_tokenizer_label = QLabel(self.base_model_box)
        self.t5_tokenizer_label.setObjectName(u"t5_tokenizer_label")
        self.formLayout_3.setWidget(3, QFormLayout.ItemRole.LabelRole, self.t5_tokenizer_label)
        self.t5_tokenizer_hLayout = QHBoxLayout()
        self.t5_tokenizer_hLayout.setObjectName(u"t5_tokenizer_hLayout")
        self.t5_tokenizer_input = DragDropLineEdit(self.base_model_box)
        self.t5_tokenizer_input.setObjectName(u"t5_tokenizer_input")
        self.t5_tokenizer_hLayout.addWidget(self.t5_tokenizer_input)
        self.t5_tokenizer_selector = QPushButton(self.base_model_box)
        self.t5_tokenizer_selector.setObjectName(u"t5_tokenizer_selector")
        self.t5_tokenizer_hLayout.addWidget(self.t5_tokenizer_selector)
        self.formLayout_3.setLayout(3, QFormLayout.ItemRole.FieldRole, self.t5_tokenizer_hLayout)

        # Precision/loading flags row
        self.model_checkbox_gridLayout = QGridLayout()
        self.model_checkbox_gridLayout.setObjectName(u"model_checkbox_gridLayout")
        self.model_checkbox_gridLayout.setVerticalSpacing(1)

        self.no_half_vae_enable = QCheckBox(self.base_model_box)
        self.no_half_vae_enable.setObjectName(u"no_half_vae_enable")
        self.model_checkbox_gridLayout.addWidget(self.no_half_vae_enable, 0, 0, 1, 1)

        self.low_ram_enable = QCheckBox(self.base_model_box)
        self.low_ram_enable.setObjectName(u"low_ram_enable")
        self.model_checkbox_gridLayout.addWidget(self.low_ram_enable, 0, 1, 1, 1)

        self.high_vram_enable = QCheckBox(self.base_model_box)
        self.high_vram_enable.setObjectName(u"high_vram_enable")
        self.model_checkbox_gridLayout.addWidget(self.high_vram_enable, 0, 2, 1, 1)

        self.FP16_enable = QCheckBox(self.base_model_box)
        self.FP16_enable.setObjectName(u"FP16_enable")
        self.model_checkbox_gridLayout.addWidget(self.FP16_enable, 1, 0, 1, 1)

        self.BF16_enable = QCheckBox(self.base_model_box)
        self.BF16_enable.setObjectName(u"BF16_enable")
        self.model_checkbox_gridLayout.addWidget(self.BF16_enable, 1, 1, 1, 1)

        self.formLayout_3.setLayout(4, QFormLayout.ItemRole.SpanningRole, self.model_checkbox_gridLayout)

        self.gridLayout_3.addWidget(self.base_model_box, 0, 0, 1, 2)

        # ---------------- Resolution + Gradient row ----------------
        self.resolution_box = QGroupBox(base_args_ui)
        self.resolution_box.setObjectName(u"resolution_box")
        self.formLayout = QFormLayout(self.resolution_box)
        self.formLayout.setObjectName(u"formLayout")
        self.label = QLabel(self.resolution_box)
        self.label.setObjectName(u"label")
        self.formLayout.setWidget(0, QFormLayout.ItemRole.LabelRole, self.label)
        self.width_input = SpinBox(self.resolution_box)
        self.width_input.setObjectName(u"width_input")
        self.width_input.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.width_input.setMinimum(1)
        self.width_input.setMaximum(16777215)
        self.width_input.setValue(1024)
        self.formLayout.setWidget(0, QFormLayout.ItemRole.FieldRole, self.width_input)
        self.height_enable = QCheckBox(self.resolution_box)
        self.height_enable.setObjectName(u"height_enable")
        self.formLayout.setWidget(1, QFormLayout.ItemRole.LabelRole, self.height_enable)
        self.height_input = SpinBox(self.resolution_box)
        self.height_input.setObjectName(u"height_input")
        self.height_input.setEnabled(False)
        self.height_input.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.height_input.setMinimum(1)
        self.height_input.setMaximum(16777215)
        self.height_input.setValue(1024)
        self.formLayout.setWidget(1, QFormLayout.ItemRole.FieldRole, self.height_input)
        self.gridLayout_3.addWidget(self.resolution_box, 1, 0, 1, 1)

        self.groupBox = QGroupBox(base_args_ui)
        self.groupBox.setObjectName(u"groupBox")
        self.horizontalLayout_8 = QHBoxLayout(self.groupBox)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.grad_checkpointing_enable = QCheckBox(self.groupBox)
        self.grad_checkpointing_enable.setObjectName(u"grad_checkpointing_enable")
        self.gridLayout.addWidget(self.grad_checkpointing_enable, 0, 0, 1, 2)
        self.grad_accumulation_enable = QCheckBox(self.groupBox)
        self.grad_accumulation_enable.setObjectName(u"grad_accumulation_enable")
        self.gridLayout.addWidget(self.grad_accumulation_enable, 1, 0, 1, 1)
        self.grad_accumulation_input = SpinBox(self.groupBox)
        self.grad_accumulation_input.setObjectName(u"grad_accumulation_input")
        self.grad_accumulation_input.setEnabled(False)
        self.grad_accumulation_input.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.grad_accumulation_input.setMinimum(1)
        self.gridLayout.addWidget(self.grad_accumulation_input, 1, 1, 1, 1)
        self.horizontalLayout_8.addLayout(self.gridLayout)
        self.gridLayout_3.addWidget(self.groupBox, 1, 1, 1, 1)

        # ---------------- Core training fields (left column) ----------------
        self.formLayout_6 = QFormLayout()
        self.formLayout_6.setObjectName(u"formLayout_6")
        self.formLayout_6.setContentsMargins(-1, -1, 3, -1)

        self.label_7 = QLabel(base_args_ui)
        self.label_7.setObjectName(u"label_7")
        self.formLayout_6.setWidget(0, QFormLayout.ItemRole.LabelRole, self.label_7)
        self.seed_input = DoubleSpinBox(base_args_ui)
        self.seed_input.setObjectName(u"seed_input")
        self.seed_input.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.seed_input.setDecimals(0)
        self.seed_input.setMinimum(-1.0)
        self.seed_input.setMaximum(4294967296.0)
        self.seed_input.setValue(42.0)
        self.formLayout_6.setWidget(0, QFormLayout.ItemRole.FieldRole, self.seed_input)

        self.max_data_loader_n_workers_label = QLabel(base_args_ui)
        self.max_data_loader_n_workers_label.setObjectName(u"max_data_loader_n_workers_label")
        self.formLayout_6.setWidget(1, QFormLayout.ItemRole.LabelRole, self.max_data_loader_n_workers_label)
        self.max_data_loader_n_workers_input = SpinBox(base_args_ui)
        self.max_data_loader_n_workers_input.setObjectName(u"max_data_loader_n_workers_input")
        self.max_data_loader_n_workers_input.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.max_data_loader_n_workers_input.setMinimum(1)
        self.max_data_loader_n_workers_input.setMaximum(64)
        self.max_data_loader_n_workers_input.setValue(1)
        self.formLayout_6.setWidget(1, QFormLayout.ItemRole.FieldRole, self.max_data_loader_n_workers_input)

        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.xformers_enable = QCheckBox(base_args_ui)
        self.xformers_enable.setObjectName(u"xformers_enable")
        self.horizontalLayout_7.addWidget(self.xformers_enable)
        self.sdpa_enable = QCheckBox(base_args_ui)
        self.sdpa_enable.setObjectName(u"sdpa_enable")
        self.horizontalLayout_7.addWidget(self.sdpa_enable)
        self.formLayout_6.setLayout(2, QFormLayout.ItemRole.SpanningRole, self.horizontalLayout_7)

        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.cache_latents_enable = QCheckBox(base_args_ui)
        self.cache_latents_enable.setObjectName(u"cache_latents_enable")
        self.horizontalLayout_5.addWidget(self.cache_latents_enable)
        self.cache_latents_to_disk_enable = QCheckBox(base_args_ui)
        self.cache_latents_to_disk_enable.setObjectName(u"cache_latents_to_disk_enable")
        self.cache_latents_to_disk_enable.setEnabled(False)
        self.horizontalLayout_5.addWidget(self.cache_latents_to_disk_enable)
        self.formLayout_6.setLayout(3, QFormLayout.ItemRole.SpanningRole, self.horizontalLayout_5)

        self.gridLayout_3.addLayout(self.formLayout_6, 2, 0, 1, 1)

        # ---------------- Core training fields (right column) ----------------
        self.formLayout_5 = QFormLayout()
        self.formLayout_5.setObjectName(u"formLayout_5")
        self.formLayout_5.setContentsMargins(3, -1, -1, -1)

        self.label_3 = QLabel(base_args_ui)
        self.label_3.setObjectName(u"label_3")
        self.formLayout_5.setWidget(0, QFormLayout.ItemRole.LabelRole, self.label_3)
        self.batch_size_input = SpinBox(base_args_ui)
        self.batch_size_input.setObjectName(u"batch_size_input")
        self.batch_size_input.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.batch_size_input.setMinimum(1)
        self.formLayout_5.setWidget(0, QFormLayout.ItemRole.FieldRole, self.batch_size_input)

        self.label_5 = QLabel(base_args_ui)
        self.label_5.setObjectName(u"label_5")
        self.formLayout_5.setWidget(1, QFormLayout.ItemRole.LabelRole, self.label_5)
        self.mixed_precision_selector = ComboBox(base_args_ui)
        self.mixed_precision_selector.addItem("")
        self.mixed_precision_selector.addItem("")
        self.mixed_precision_selector.addItem("")
        self.mixed_precision_selector.setObjectName(u"mixed_precision_selector")
        self.mixed_precision_selector.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.formLayout_5.setWidget(1, QFormLayout.ItemRole.FieldRole, self.mixed_precision_selector)

        self.label_6 = QLabel(base_args_ui)
        self.label_6.setObjectName(u"label_6")
        self.formLayout_5.setWidget(2, QFormLayout.ItemRole.LabelRole, self.label_6)
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.max_train_selector = ComboBox(base_args_ui)
        self.max_train_selector.addItem("")
        self.max_train_selector.addItem("")
        self.max_train_selector.setObjectName(u"max_train_selector")
        self.max_train_selector.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.horizontalLayout_3.addWidget(self.max_train_selector)
        self.max_train_input = SpinBox(base_args_ui)
        self.max_train_input.setObjectName(u"max_train_input")
        self.max_train_input.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.max_train_input.setMinimum(1)
        self.max_train_input.setMaximum(16777215)
        self.horizontalLayout_3.addWidget(self.max_train_input)
        self.formLayout_5.setLayout(2, QFormLayout.ItemRole.FieldRole, self.horizontalLayout_3)

        self.keep_tokens_seperator_enable = QCheckBox(base_args_ui)
        self.keep_tokens_seperator_enable.setObjectName(u"keep_tokens_seperator_enable")
        self.formLayout_5.setWidget(3, QFormLayout.ItemRole.LabelRole, self.keep_tokens_seperator_enable)
        self.keep_tokens_seperator_input = LineEditWithHighlight(base_args_ui)
        self.keep_tokens_seperator_input.setObjectName(u"keep_tokens_seperator_input")
        self.keep_tokens_seperator_input.setEnabled(False)
        self.formLayout_5.setWidget(3, QFormLayout.ItemRole.FieldRole, self.keep_tokens_seperator_input)

        self.global_protected_tags_file_enable = QCheckBox(base_args_ui)
        self.global_protected_tags_file_enable.setObjectName(u"global_protected_tags_file_enable")
        self.formLayout_5.setWidget(4, QFormLayout.ItemRole.LabelRole, self.global_protected_tags_file_enable)
        self.global_protected_tags_file_hLayout = QHBoxLayout()
        self.global_protected_tags_file_hLayout.setObjectName(u"global_protected_tags_file_hLayout")
        self.global_protected_tags_file_input = DragDropLineEdit(base_args_ui)
        self.global_protected_tags_file_input.setObjectName(u"global_protected_tags_file_input")
        self.global_protected_tags_file_input.setEnabled(False)
        self.global_protected_tags_file_hLayout.addWidget(self.global_protected_tags_file_input)
        self.global_protected_tags_file_selector = QPushButton(base_args_ui)
        self.global_protected_tags_file_selector.setObjectName(u"global_protected_tags_file_selector")
        self.global_protected_tags_file_selector.setEnabled(False)
        self.global_protected_tags_file_hLayout.addWidget(self.global_protected_tags_file_selector)
        self.formLayout_5.setLayout(4, QFormLayout.ItemRole.FieldRole, self.global_protected_tags_file_hLayout)

        self.gridLayout_3.addLayout(self.formLayout_5, 2, 1, 1, 1)

        # ---------------- Anima sampling row ----------------
        self.anima_sampling_box = QGroupBox(base_args_ui)
        self.anima_sampling_box.setObjectName(u"anima_sampling_box")
        self.anima_sampling_layout = QFormLayout(self.anima_sampling_box)
        self.anima_sampling_layout.setObjectName(u"anima_sampling_layout")

        self.timestep_sampling_label = QLabel(self.anima_sampling_box)
        self.timestep_sampling_label.setObjectName(u"timestep_sampling_label")
        self.anima_sampling_layout.setWidget(0, QFormLayout.ItemRole.LabelRole, self.timestep_sampling_label)
        self.timestep_sampling_selector = ComboBox(self.anima_sampling_box)
        self.timestep_sampling_selector.addItem("sigma")
        self.timestep_sampling_selector.addItem("uniform")
        self.timestep_sampling_selector.addItem("sigmoid")
        self.timestep_sampling_selector.addItem("shift")
        self.timestep_sampling_selector.addItem("flux_shift")
        self.timestep_sampling_selector.setObjectName(u"timestep_sampling_selector")
        self.timestep_sampling_selector.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.anima_sampling_layout.setWidget(0, QFormLayout.ItemRole.FieldRole, self.timestep_sampling_selector)

        self.discrete_flow_shift_label = QLabel(self.anima_sampling_box)
        self.discrete_flow_shift_label.setObjectName(u"discrete_flow_shift_label")
        self.anima_sampling_layout.setWidget(1, QFormLayout.ItemRole.LabelRole, self.discrete_flow_shift_label)
        self.discrete_flow_shift_input = DoubleSpinBox(self.anima_sampling_box)
        self.discrete_flow_shift_input.setObjectName(u"discrete_flow_shift_input")
        self.discrete_flow_shift_input.setDecimals(2)
        self.discrete_flow_shift_input.setSingleStep(0.1)
        self.discrete_flow_shift_input.setValue(3.0)
        self.anima_sampling_layout.setWidget(1, QFormLayout.ItemRole.FieldRole, self.discrete_flow_shift_input)

        self.sigmoid_scale_label = QLabel(self.anima_sampling_box)
        self.sigmoid_scale_label.setObjectName(u"sigmoid_scale_label")
        self.anima_sampling_layout.setWidget(2, QFormLayout.ItemRole.LabelRole, self.sigmoid_scale_label)
        self.sigmoid_scale_input = DoubleSpinBox(self.anima_sampling_box)
        self.sigmoid_scale_input.setObjectName(u"sigmoid_scale_input")
        self.sigmoid_scale_input.setDecimals(2)
        self.sigmoid_scale_input.setSingleStep(0.1)
        self.sigmoid_scale_input.setValue(1.0)
        self.anima_sampling_layout.setWidget(2, QFormLayout.ItemRole.FieldRole, self.sigmoid_scale_input)

        self.qwen3_max_token_label = QLabel(self.anima_sampling_box)
        self.qwen3_max_token_label.setObjectName(u"qwen3_max_token_label")
        self.anima_sampling_layout.setWidget(3, QFormLayout.ItemRole.LabelRole, self.qwen3_max_token_label)
        self.qwen3_max_token_input = SpinBox(self.anima_sampling_box)
        self.qwen3_max_token_input.setObjectName(u"qwen3_max_token_input")
        self.qwen3_max_token_input.setMinimum(1)
        self.qwen3_max_token_input.setMaximum(16777215)
        self.qwen3_max_token_input.setValue(512)
        self.anima_sampling_layout.setWidget(3, QFormLayout.ItemRole.FieldRole, self.qwen3_max_token_input)

        self.t5_max_token_label = QLabel(self.anima_sampling_box)
        self.t5_max_token_label.setObjectName(u"t5_max_token_label")
        self.anima_sampling_layout.setWidget(4, QFormLayout.ItemRole.LabelRole, self.t5_max_token_label)
        self.t5_max_token_input = SpinBox(self.anima_sampling_box)
        self.t5_max_token_input.setObjectName(u"t5_max_token_input")
        self.t5_max_token_input.setMinimum(1)
        self.t5_max_token_input.setMaximum(16777215)
        self.t5_max_token_input.setValue(512)
        self.anima_sampling_layout.setWidget(4, QFormLayout.ItemRole.FieldRole, self.t5_max_token_input)

        self.gridLayout_3.addWidget(self.anima_sampling_box, 3, 0, 1, 2)

        # ---------------- Anima memory / attention row ----------------
        self.anima_memory_box = QGroupBox(base_args_ui)
        self.anima_memory_box.setObjectName(u"anima_memory_box")
        self.anima_memory_layout = QGridLayout(self.anima_memory_box)
        self.anima_memory_layout.setObjectName(u"anima_memory_layout")

        self.vae_chunk_size_label = QLabel(self.anima_memory_box)
        self.vae_chunk_size_label.setObjectName(u"vae_chunk_size_label")
        self.anima_memory_layout.addWidget(self.vae_chunk_size_label, 0, 0, 1, 1)
        self.vae_chunk_size_input = SpinBox(self.anima_memory_box)
        self.vae_chunk_size_input.setObjectName(u"vae_chunk_size_input")
        self.vae_chunk_size_input.setMinimum(0)
        self.vae_chunk_size_input.setMaximum(16777215)
        self.vae_chunk_size_input.setSingleStep(2)
        self.vae_chunk_size_input.setValue(0)
        self.anima_memory_layout.addWidget(self.vae_chunk_size_input, 0, 1, 1, 1)

        self.blocks_to_swap_label = QLabel(self.anima_memory_box)
        self.blocks_to_swap_label.setObjectName(u"blocks_to_swap_label")
        self.anima_memory_layout.addWidget(self.blocks_to_swap_label, 0, 2, 1, 1)
        self.blocks_to_swap_input = SpinBox(self.anima_memory_box)
        self.blocks_to_swap_input.setObjectName(u"blocks_to_swap_input")
        self.blocks_to_swap_input.setMinimum(0)
        self.blocks_to_swap_input.setMaximum(100)
        self.blocks_to_swap_input.setValue(0)
        self.anima_memory_layout.addWidget(self.blocks_to_swap_input, 0, 3, 1, 1)

        self.vae_disable_cache_enable = QCheckBox(self.anima_memory_box)
        self.vae_disable_cache_enable.setObjectName(u"vae_disable_cache_enable")
        self.anima_memory_layout.addWidget(self.vae_disable_cache_enable, 0, 4, 1, 1)

        self.flash_attn_enable = QCheckBox(self.anima_memory_box)
        self.flash_attn_enable.setObjectName(u"flash_attn_enable")
        self.anima_memory_layout.addWidget(self.flash_attn_enable, 1, 0, 1, 1)
        self.split_attn_enable = QCheckBox(self.anima_memory_box)
        self.split_attn_enable.setObjectName(u"split_attn_enable")
        self.anima_memory_layout.addWidget(self.split_attn_enable, 1, 1, 1, 1)
        self.unsloth_offload_checkpointing = QCheckBox(self.anima_memory_box)
        self.unsloth_offload_checkpointing.setObjectName(u"unsloth_offload_checkpointing")
        self.anima_memory_layout.addWidget(self.unsloth_offload_checkpointing, 1, 2, 1, 3)

        self.gridLayout_3.addWidget(self.anima_memory_box, 4, 0, 1, 2)

        # ---------------- Anima flow matching row ----------------
        self.anima_flow_box = QGroupBox(base_args_ui)
        self.anima_flow_box.setObjectName(u"anima_flow_box")
        self.anima_flow_layout = QGridLayout(self.anima_flow_box)
        self.anima_flow_layout.setObjectName(u"anima_flow_layout")

        self.flow_use_ot_enable = QCheckBox(self.anima_flow_box)
        self.flow_use_ot_enable.setObjectName(u"flow_use_ot_enable")
        self.flow_use_ot_enable.setChecked(True)
        self.anima_flow_layout.addWidget(self.flow_use_ot_enable, 0, 0, 1, 1)

        self.contrastive_flow_matching_enable = QCheckBox(self.anima_flow_box)
        self.contrastive_flow_matching_enable.setObjectName(u"contrastive_flow_matching_enable")
        self.anima_flow_layout.addWidget(self.contrastive_flow_matching_enable, 0, 1, 1, 1)

        self.cfm_lambda_label = QLabel(self.anima_flow_box)
        self.cfm_lambda_label.setObjectName(u"cfm_lambda_label")
        self.anima_flow_layout.addWidget(self.cfm_lambda_label, 0, 2, 1, 1)
        self.cfm_lambda_input = DoubleSpinBox(self.anima_flow_box)
        self.cfm_lambda_input.setObjectName(u"cfm_lambda_input")
        self.cfm_lambda_input.setDecimals(3)
        self.cfm_lambda_input.setMinimum(-100.0)
        self.cfm_lambda_input.setMaximum(100.0)
        self.cfm_lambda_input.setSingleStep(0.001)
        self.cfm_lambda_input.setValue(0.02)
        self.cfm_lambda_input.setEnabled(False)
        self.anima_flow_layout.addWidget(self.cfm_lambda_input, 0, 3, 1, 1)

        self.gridLayout_3.addWidget(self.anima_flow_box, 5, 0, 1, 2)

        # ---------------- Comment ----------------
        self.formLayout_2 = QFormLayout()
        self.formLayout_2.setObjectName(u"formLayout_2")
        self.comment_enable = QCheckBox(base_args_ui)
        self.comment_enable.setObjectName(u"comment_enable")
        self.formLayout_2.setWidget(0, QFormLayout.ItemRole.LabelRole, self.comment_enable)
        self.comment_input = QTextEdit(base_args_ui)
        self.comment_input.setObjectName(u"comment_input")
        self.comment_input.setEnabled(False)
        self.formLayout_2.setWidget(0, QFormLayout.ItemRole.FieldRole, self.comment_input)
        self.gridLayout_3.addLayout(self.formLayout_2, 6, 0, 1, 2)

        self.retranslateUi(base_args_ui)

    def retranslateUi(self, base_args_ui):
        _t = QCoreApplication.translate
        base_args_ui.setWindowTitle(_t("base_args_ui", u"Form", None))

        # Models
        self.base_model_box.setTitle(_t("base_args_ui", u"Anima Models", None))
        self.base_model_label.setText(_t("base_args_ui", u"DiT Model", None))
        self.base_model_input.setProperty(u"placeholderText", _t("base_args_ui", u"Path to Anima DiT model (.safetensors)", None))
        self.base_model_input.setToolTip(_t("base_args_ui", u"Path to the Anima DiT model file. Maps to --pretrained_model_name_or_path.", None))
        self.base_model_selector.setText("")
        self.qwen3_model_label.setText(_t("base_args_ui", u"Qwen3 Model", None))
        self.qwen3_model_input.setProperty(u"placeholderText", _t("base_args_ui", u"Qwen3-0.6B file or HF directory", None))
        self.qwen3_model_input.setToolTip(_t("base_args_ui", u"Path to the Qwen3-0.6B text encoder. Maps to --qwen3.", None))
        self.qwen3_model_selector.setText("")
        self.vae_label.setText(_t("base_args_ui", u"VAE", None))
        self.vae_input.setProperty(u"placeholderText", _t("base_args_ui", u"Qwen-Image VAE (.safetensors)", None))
        self.vae_input.setToolTip(_t("base_args_ui", u"Path to the Qwen-Image VAE. Maps to --vae.", None))
        self.vae_selector.setText("")
        self.t5_tokenizer_label.setText(_t("base_args_ui", u"T5 Tokenizer", None))
        self.t5_tokenizer_input.setProperty(u"placeholderText", _t("base_args_ui", u"Optional T5 tokenizer directory", None))
        self.t5_tokenizer_input.setToolTip(_t("base_args_ui", u"Optional. Path to the T5 tokenizer directory. Maps to --t5_tokenizer_path.", None))
        self.t5_tokenizer_selector.setText("")

        self.no_half_vae_enable.setText(_t("base_args_ui", u"No Half VAE", None))
        self.no_half_vae_enable.setToolTip(_t("base_args_ui", u"Load the VAE in FP32. Roughly doubles VRAM for VAE workloads.", None))
        self.low_ram_enable.setText(_t("base_args_ui", u"Low RAM", None))
        self.high_vram_enable.setText(_t("base_args_ui", u"High VRAM", None))
        self.FP16_enable.setText(_t("base_args_ui", u"Full FP16", None))
        self.BF16_enable.setText(_t("base_args_ui", u"Full BF16", None))

        # Resolution / gradient
        self.resolution_box.setTitle(_t("base_args_ui", u"Resolution", None))
        self.label.setText(_t("base_args_ui", u"Width", None))
        self.height_enable.setText(_t("base_args_ui", u"Height", None))
        self.groupBox.setTitle(_t("base_args_ui", u"Gradient", None))
        self.grad_checkpointing_enable.setText(_t("base_args_ui", u"Gradient Checkpointing", None))
        self.grad_accumulation_enable.setText(_t("base_args_ui", u"Gradient Accumulation", None))

        # Core fields
        self.label_3.setText(_t("base_args_ui", u"Batch Size", None))
        self.label_5.setText(_t("base_args_ui", u"Training Precision", None))
        self.mixed_precision_selector.setItemText(0, _t("base_args_ui", u"fp16", None))
        self.mixed_precision_selector.setItemText(1, _t("base_args_ui", u"bf16", None))
        self.mixed_precision_selector.setItemText(2, _t("base_args_ui", u"float", None))
        self.label_6.setText(_t("base_args_ui", u"Max Training Time", None))
        self.max_train_selector.setItemText(0, _t("base_args_ui", u"Epochs", None))
        self.max_train_selector.setItemText(1, _t("base_args_ui", u"Steps", None))
        self.label_7.setText(_t("base_args_ui", u"Seed", None))
        self.max_data_loader_n_workers_label.setText(_t("base_args_ui", u"Max Data Loader Workers", None))
        self.xformers_enable.setText(_t("base_args_ui", u"xFormers", None))
        self.sdpa_enable.setText(_t("base_args_ui", u"SDPA", None))
        self.cache_latents_enable.setText(_t("base_args_ui", u"Cache Latents", None))
        self.cache_latents_to_disk_enable.setText(_t("base_args_ui", u"To Disk", None))
        self.keep_tokens_seperator_enable.setText(_t("base_args_ui", u"Keep Tags Seperator", None))
        self.global_protected_tags_file_enable.setText(_t("base_args_ui", u"Protected Tags File (Global)", None))
        self.global_protected_tags_file_selector.setText("")

        # Anima sampling
        self.anima_sampling_box.setTitle(_t("base_args_ui", u"Anima Sampling", None))
        self.timestep_sampling_label.setText(_t("base_args_ui", u"Timestep Sampling", None))
        self.timestep_sampling_selector.setToolTip(_t("base_args_ui", u"Method for sampling timesteps. 'sigmoid' (logit normal) is recommended for Anima.", None))
        self.discrete_flow_shift_label.setText(_t("base_args_ui", u"Discrete Flow Shift", None))
        self.discrete_flow_shift_input.setToolTip(_t("base_args_ui", u"Shift value for the Rectified Flow timestep distribution. Default 3.0.", None))
        self.sigmoid_scale_label.setText(_t("base_args_ui", u"Sigmoid Scale", None))
        self.sigmoid_scale_input.setToolTip(_t("base_args_ui", u"Scale factor for logit_normal (sigmoid) timestep sampling. Default 1.0.", None))
        self.qwen3_max_token_label.setText(_t("base_args_ui", u"Qwen3 Max Tokens", None))
        self.t5_max_token_label.setText(_t("base_args_ui", u"T5 Max Tokens", None))

        # Anima memory / attention
        self.anima_memory_box.setTitle(_t("base_args_ui", u"Anima Memory / Attention", None))
        self.vae_chunk_size_label.setText(_t("base_args_ui", u"VAE Chunk Size", None))
        self.vae_chunk_size_input.setToolTip(_t("base_args_ui", u"Spatial chunk size for the Qwen-Image VAE. 0 disables chunking.", None))
        self.blocks_to_swap_label.setText(_t("base_args_ui", u"Blocks to Swap", None))
        self.blocks_to_swap_input.setToolTip(_t("base_args_ui", u"Number of transformer blocks to swap CPU/GPU. 0 disables swapping.", None))
        self.vae_disable_cache_enable.setText(_t("base_args_ui", u"VAE Disable Cache", None))
        self.flash_attn_enable.setText(_t("base_args_ui", u"Flash Attention", None))
        self.flash_attn_enable.setToolTip(_t("base_args_ui", u"Use Flash Attention. Maps to --attn_mode flash. Requires flash-attn package.", None))
        self.split_attn_enable.setText(_t("base_args_ui", u"Split Attention", None))
        self.split_attn_enable.setToolTip(_t("base_args_ui", u"Maps to --split_attn. Auto-enabled (and locked) when xFormers is selected.", None))
        self.unsloth_offload_checkpointing.setText(_t("base_args_ui", u"Unsloth Offload Checkpointing", None))

        # Anima flow matching
        self.anima_flow_box.setTitle(_t("base_args_ui", u"Anima Flow Matching", None))
        self.flow_use_ot_enable.setText(_t("base_args_ui", u"Cosine Optimal Transport", None))
        self.flow_use_ot_enable.setToolTip(_t("base_args_ui", u"Pair latents and noise within a batch using cosine optimal transport instead of fixed pairing. Recommended for Rectified Flow. Maps to --flow_use_ot.", None))
        self.contrastive_flow_matching_enable.setText(_t("base_args_ui", u"Contrastive Flow Matching", None))
        self.contrastive_flow_matching_enable.setToolTip(_t("base_args_ui", u"Enable Contrastive Flow Matching (ΔFM): subtracts a negative contrastive loss term to sharpen results. Maps to --contrastive_flow_matching.", None))
        self.cfm_lambda_label.setText(_t("base_args_ui", u"CFM Lambda", None))
        self.cfm_lambda_input.setToolTip(_t("base_args_ui", u"Weight for the ΔFM contrastive term. Anima default 0.02. Maps to --cfm_lambda.", None))

        # Comment
        self.comment_enable.setText(_t("base_args_ui", u"Comment", None))
        self.comment_input.setPlaceholderText(_t("base_args_ui", u"Enter a comment for the metadata", None))
